server/cart/urls.py
from django.urls import path

from .views import (
    cart_view, PurchaseDetailView
)


app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart'),
    path('<int:pk>/', PurchaseDetailView.as_view(), name='detail'),
]

server/main/urls.py
from django.urls import path

from .views import product_list


app_name = 'main'

urlpatterns = [
    path('', product_list, name='list'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

router = [
    path('products/', include('main.routes')),
    path('cart/', include('cart.routes')),
]

urlpatterns = [
    path('api/', include(router)),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),
]

server/cart/models.py
import json
from functools import reduce
from django.apps import apps
from django.db import models
from django.core.exceptions import ValidationError


class Purchase(models.Model):
    user = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    @property
    def cost(self):
        return reduce(
            lambda total, itm: total + itm.product.cost,
            self.items.all(),
            0 
        )

    @property
    def count(self):
        return reduce(
            lambda total, itm: total + itm.value,
            self.items.all(),
            0
        )

    def __str__(self):
        full_name = self.user.get_full_name()
        title = full_name if full_name else self.user.username
        return f'{title} {self.created.strftime("%Y-%m-%d %H:%M")}'
        

class PurchaseItem(models.Model):
    purchase = models.ForeignKey(
        Purchase,
        on_delete=models.CASCADE,
        related_name='items'
    )
    product = models.ForeignKey(
        'main.Product',
        on_delete=models.CASCADE,
    )
    value = models.IntegerField()

    def __str__(self):
        return self.product.title

server/main/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=150)
    cost = models.DecimalField(
        max_digits=8, 
        decimal_places=2,
        default=0,
    )

    def __str__(self):
        return self.title

server/cart/routes.py
from django.urls import path

from .views import PurchaseCreateView


app_name = 'cart_api'

urlpatterns = [
    path('create/', PurchaseCreateView.as_view(), name='create'),
]

server/cart/views.py
import json
from functools import reduce
from django.apps import apps
from django.db.models import Q
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import ( 
    View, DetailView
)

from .models import Purchase


def cart_view(request):
    return render(request, 'cart/cart.html')


class PurchaseCreateView(LoginRequiredMixin, View):
    login_url = ''
    product_model = apps.get_model('main', 'product')

    def post(self, request):
        data = json.loads(request.body)

        product_list = self.product_model.objects.filter(
            reduce(
                lambda store, key: store | Q(pk=key),
                data.keys(),
                Q()
            )
        )

        obj = Purchase.objects.create(
            user=request.user,
        )
        
        for product in product_list:
            obj.items.create(
                product=product,
                value=data[str(product.id)],
            )

        return JsonResponse(
            {
                'success_url': reverse(
                    'cart:detail',
                    kwargs={'pk': obj.id}
                )
            }
        )


class PurchaseDetailView(DetailView):
    model = Purchase
    template_name = 'cart/detail.html'

server/main/routes.py
from django.urls import path

from .views import product_json_list


app_name = 'rest_main'

urlpatterns = [
    path('', product_json_list, name='list'),
]

server/main/views.py
from functools import reduce
from django.db.models import Q
from django.shortcuts import (
    get_list_or_404, get_object_or_404, render
)
from django.http import JsonResponse

from .models import Product


def product_json_list(request):
    query_params = (
        (key, list(map(int, value.split(','))) if key.endswith('_in') else value)
        for key, value in request.GET.items()
    )
    query = get_list_or_404(
        Product,
        reduce(
            lambda store, itm: store | Q(**{itm[0]: itm[1]}),
            query_params,
            Q()
        )
    )

    return JsonResponse(
        list(
            map(
                lambda itm: {
                    'id': itm.id,
                    'title': itm.title
                },
                query
            )
        ),
        safe=False
    )


def product_list(request):
    query = get_list_or_404(Product)

    return render(
        request, 
        'main/list.html', 
        {'object_list': query}
    )

server/cart/templates/cart/cart.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %}
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'cart/css/products.css' %}">
{% endblock %}

{% block content %}
{% csrf_token %}
<h1 class="cart-title">
    Cart page
</h1>
<ul class="product-list"></ul>
<div class="control-panel"></div>
{% endblock %}

{% block page_js %}
<script src="{% static 'server/js/counter.js' %}"></script>
<script src="{% static 'cart/js/submit.js' %}"></script>
<script src="{% static 'cart/js/items.js' %}"></script>

<script>
    const emptyText = 'Корзина пуста';
    const mainUrl = '{% url "main:list" %}';
    const createPurchaseUrl = '{% url "cart_api:create" %}';
    const tokenInput = document.querySelector('[name=csrfmiddlewaretoken]');
    const productsList = document.querySelector('.product-list');
    const controlPanlel = document.querySelector('.control-panel');
    const items = getLocalValue('products');
    const identityList = Object.keys(items);

    if (identityList.length > 0) {
        const productsUrl = `{% url 'rest_main:list' %}?id__in=${identityList.join(',')}`;
    
        fetch(productsUrl)
            .then(response => response.json())
            .then(data => {
                data.map(
                    itm => productsList.innerHTML += renderItem(itm, items[itm.id])
                )
            })

        controlPanlel.appendChild(
            createCartSubmit(createPurchaseUrl, tokenInput.value)
        );
    } else {
        productsList.appendChild(
            createEmptyMock(mainUrl, emptyText)
        );
    }
</script>

{% endblock %}

server/cart/templates/cart/detail.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %}
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'cart/css/products.css' %}">
<link rel="stylesheet" href="{% static 'cart/css/total.css' %}">
{% endblock %}

{% block content %}
<h1 class="cart-title">
    {{ object }}
</h1>
<ul class="product-list">
    {% for itm in object.items.all %}
    <li class="product-item">
        <span class="product-item__title">{{ itm.product.title }}</span>
        <span class="product-item__count">{{ itm.value }}</span>
    </li>
    {% endfor %}
</ul>
<ul class="total-list">
    <li class="total-item total-item-count">
        <span>Total count</span>
        <span>{{ object.count }}</span>
    </li>
    <li class="total-item total-item_cost">
        <span>Total cost</span>
        <span>{{ object.cost }}</span>
    </li>
</ul>
{% endblock %}

server/main/templates/main/list.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %}
Produts list
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'main/css/products.css' %}">
{% endblock %}

{% block content %}
<h1 class="product-title">
    Products list
</h1>
<ul class="product-list">
    {% for obj in object_list %}
    <li id="product-item-{{ obj.id }}" class="product-item">
        <div class="product-item__wrapper product-item__wrapper_title">
            <span class="product-item__title">
                {{ obj.title }}
            </span>
        </div>
        <div class="product-item__wrapper product-item__wrapper_button">
            <button itemid="{{ obj.id }}" class="product-item__button">
                <span class="product-item__button-inner">
                    Добавить в корзину
                </span>
            </button>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

{% block page_js %}
<script src="{% static 'server/js/counter.js' %}"></script>
<script>
    const items = document.querySelectorAll('.product-item');
    items.forEach(
        itm => {
            const btn = itm.querySelector('button')
            btn.addEventListener(
                'click',
                evt => { 
                    incLocalValue(
                        'products', btn.getAttribute('itemid')
                    ) 
                }
            )
        }
    );
</script>
{% endblock %}

server/server/templates/master.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        {% block page_title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'server/css/master.css' %}">
    {% block page_styles %}
    {% endblock %}
</head>
<body>
    <header>
        <nav>
            <ul class="site-menu">
                <a href="{% url 'main:list' %}" class="site-menu__item">
                    Главная
                </a>
                <a href="{% url 'cart:cart' %}" class="site-menu__item">
                    Корзина
                </a>
            </ul>
        </nav>
    </header>

    <section class="page">
        {% block content %}
        {% endblock %}
    </section>
    {% block page_js %}
    {% endblock %}
</body>
</html>